FROM ghcr.io/eclipse-slm/information-receiving-service/base:1.0.0-SNAPSHOT

ENV COUCHDB_HOST=couch-db \
    COUCHDB_PORT=5984 \
    COUCHDB_USERNAME=username \
    COUCHDB_PASSWORD=password \
    GC_DELETE_IF_SOURCE_NOT_FOUND=false

CMD python gc.py