name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MAVEN_CLI_OPTS: "-T 8 -s ci/ci_maven_settings.xml --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true"
      MAVEN_PROFILES: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: s4u/maven-settings-action@v4.0.0
        with:
          path: ci/ci_maven_settings.xml
          githubServer: false
          servers: '[
            {
              "id": "ghcr.io",
              "username": "${{github.actor}}",
              "password": "${{secrets.GITHUB_TOKEN}}"
            },
            {
              "id": "github",
              "username": "${{github.actor}}",
              "password": "${{secrets.GITHUB_TOKEN}}"
            }
          ]'

      - name: Build with Maven and push Docker Images
        if: github.event_name != 'pull_request' && (github.ref_name == 'develop' || github.ref_name == 'main' || startsWith(github.ref_name, 'release/'))
        run: mvn $MAVEN_PROFILES $MAVEN_CLI_OPTS --projects '${{ matrix.build.maven-projects }}' deploy
      - name: Build with Maven
        if: github.event_name == 'pull_request' || startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'fix/')
        run: mvn $MAVEN_PROFILES $MAVEN_CLI_OPTS --projects '${{ matrix.build.maven-projects }}' verify